"""Live model drift monitor.

Uses a Page-Hinkley style test on realised daily rank IC. It is deliberately
small and conservative: replay rows are excluded, because the live model should
be judged on signals generated by the running app.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
import json
import logging
from pathlib import Path

import pandas as pd
import numpy as np

import config
from engine.paper_trading import _connect

logger = logging.getLogger(__name__)

STATUS_PATH = Path("feature_cache") / "drift_status.json"


@dataclass(frozen=True)
class DriftStatus:
    drift_detected: bool
    latest_ic: float | None
    mean_ic: float | None
    n_days: int
    reason: str = ""
    factor_drift: list[dict] | None = None


def _rank_ic_by_day(horizon_col: str = "return_10d", min_names: int = 5) -> list[float]:
    with _connect() as conn:
        rows = conn.execute(
            f"""SELECT run_date, final_rank, aggregate_score, {horizon_col} AS fwd_return
                FROM signal_backtest
                WHERE source NOT LIKE 'replay_pit_%'
                  AND {horizon_col} IS NOT NULL
                  AND (final_rank IS NOT NULL OR aggregate_score IS NOT NULL)"""
        ).fetchall()
    if not rows:
        return []
    df = pd.DataFrame([dict(r) for r in rows])
    df["day"] = df["run_date"].astype(str).str.slice(0, 10)
    values: list[float] = []
    for _day, group in df.groupby("day"):
        if len(group) < min_names:
            continue
        score = group["final_rank"].fillna(group["aggregate_score"])
        ic = score.rank().corr(group["fwd_return"].rank())
        if pd.notna(ic):
            values.append(float(ic))
    return values


def page_hinkley(values: list[float], *, delta: float = 0.002, threshold: float = 0.08, alpha: float = 0.99) -> bool:
    """Return True when the series shows a meaningful negative break."""
    if len(values) < 10:
        return False
    mean = values[0]
    cumulative = 0.0
    min_cumulative = 0.0
    for value in values[1:]:
        mean = alpha * mean + (1.0 - alpha) * value
        cumulative += mean - value - delta
        min_cumulative = min(min_cumulative, cumulative)
        if cumulative - min_cumulative > threshold:
            return True
    return False


def _ks_pvalue(sample_a: list[float], sample_b: list[float]) -> tuple[float, float]:
    a = np.asarray(sample_a, dtype=float)
    b = np.asarray(sample_b, dtype=float)
    a = a[np.isfinite(a)]
    b = b[np.isfinite(b)]
    if len(a) < 2 or len(b) < 2:
        return 0.0, 1.0
    try:
        from scipy.stats import ks_2samp
        stat, pval = ks_2samp(a, b)
        return float(stat), float(pval)
    except Exception:
        # Asymptotic two-sample KS approximation.
        data = np.sort(np.concatenate([a, b]))
        cdf_a = np.searchsorted(np.sort(a), data, side="right") / len(a)
        cdf_b = np.searchsorted(np.sort(b), data, side="right") / len(b)
        stat = float(np.max(np.abs(cdf_a - cdf_b)))
        n_eff = len(a) * len(b) / max(len(a) + len(b), 1)
        pval = float(min(1.0, 2.0 * np.exp(-2.0 * n_eff * stat * stat)))
        return stat, pval


def factor_distribution_ks(
    *,
    columns: list[str] | None = None,
    p_threshold: float | None = None,
    min_sample: int | None = None,
) -> list[dict]:
    """Compare recent live factor distributions with replay/baseline rows."""
    columns = columns or list(getattr(config, "DRIFT_KS_COLUMNS", []))
    p_threshold = float(p_threshold or getattr(config, "DRIFT_KS_P_THRESHOLD", 0.01))
    min_sample = int(min_sample or getattr(config, "DRIFT_KS_MIN_SAMPLE", 30))
    if not columns:
        return []

    safe_cols = [c for c in columns if c.replace("_", "").isalnum()]
    if not safe_cols:
        return []
    col_sql = ", ".join(safe_cols)
    with _connect() as conn:
        recent_rows = conn.execute(
            f"""SELECT {col_sql}
                FROM signal_backtest
                WHERE source NOT LIKE 'replay_pit_%'
                  AND date(run_date) >= date('now', '-45 days')"""
        ).fetchall()
        baseline_rows = conn.execute(
            f"""SELECT {col_sql}
                FROM signal_backtest
                WHERE source LIKE 'replay_pit_%'
                   OR date(run_date) < date('now', '-45 days')
                ORDER BY date(run_date) DESC
                LIMIT 20000"""
        ).fetchall()

    if not recent_rows or not baseline_rows:
        return []

    recent = pd.DataFrame([dict(r) for r in recent_rows])
    baseline = pd.DataFrame([dict(r) for r in baseline_rows])
    drifts: list[dict] = []
    for col in safe_cols:
        if col not in recent or col not in baseline:
            continue
        a = recent[col].dropna().astype(float).tolist()
        b = baseline[col].dropna().astype(float).tolist()
        if len(a) < min_sample or len(b) < min_sample:
            continue
        stat, pval = _ks_pvalue(a, b)
        if pval < p_threshold:
            drifts.append({
                "factor": col,
                "ks_stat": round(stat, 4),
                "p_value": round(pval, 6),
                "recent_n": len(a),
                "baseline_n": len(b),
            })
    return drifts


def get_drift_status(
    *,
    horizon_col: str | None = None,
    min_days: int | None = None,
    write: bool = False,
) -> DriftStatus:
    horizon_col = horizon_col or getattr(config, "DRIFT_MONITOR_HORIZON_COL", "return_10d")
    min_days = int(min_days or getattr(config, "DRIFT_MONITOR_MIN_DAYS", 20))
    values = _rank_ic_by_day(horizon_col=horizon_col)
    factor_drift = factor_distribution_ks()
    if len(values) < min_days:
        status = DriftStatus(
            False,
            values[-1] if values else None,
            None,
            len(values),
            "insufficient_live_ic_history",
            factor_drift,
        )
    else:
        window = values[-min_days:]
        drift = page_hinkley(
            window,
            delta=float(getattr(config, "DRIFT_MONITOR_DELTA", 0.002)),
            threshold=float(getattr(config, "DRIFT_MONITOR_THRESHOLD", 0.08)),
            alpha=float(getattr(config, "DRIFT_MONITOR_ALPHA", 0.99)),
        )
        status = DriftStatus(
            drift,
            window[-1] if window else None,
            float(pd.Series(window).mean()) if window else None,
            len(window),
            "page_hinkley_negative_ic_break" if drift else "",
            factor_drift,
        )
    if write:
        STATUS_PATH.parent.mkdir(parents=True, exist_ok=True)
        STATUS_PATH.write_text(json.dumps({
            "updated_at": datetime.now().isoformat(),
            **status.__dict__,
        }, indent=2), encoding="utf-8")
    return status


if __name__ == "__main__":
    print(get_drift_status(write=True))
